import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import * as curlconverter from "curlconverter";
import { GoogleGenAI } from "@google/genai";
import { parseCurlAdvanced, fallbackCurlToCode } from "./src/utils/curlParser";

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: "50mb" }));
  app.use(express.urlencoded({ extended: true, limit: "50mb" }));

  // Convert cURL to Python or other target languages
  app.post("/api/convert", (req, res) => {
    const target = req.body?.target || "python-requests";
    try {
      const { curlCommand, options = {} } = req.body;

      if (!curlCommand || typeof curlCommand !== "string") {
        return res.status(400).json({ error: "Lütfen geçerli bir cURL komutu girin." });
      }

      const trimmedCurl = curlCommand.trim();
      let code = convertCurlWithFallbacks(trimmedCurl, target, options);

      // Apply custom post-processing options if requested
      if (options.addTryExcept && code && target.startsWith("python")) {
        code = wrapTryExcept(code);
      }

      if (options.addComments && code) {
        const lang = target.startsWith("python") ? "#" : "//";
        code = `${lang} Auto-generated by Curl2Py Pro\n${lang} Tarih: ${new Date().toISOString().split("T")[0]}\n\n` + code;
      }

      if (options.useSession && target === "python-requests" && code) {
        code = code.replace(/response = requests\.(get|post|put|delete|patch|head|options)\(/, "session = requests.Session()\nresponse = session.$1(");
      }

      res.json({ success: true, code, target });
    } catch (err: any) {
      console.error("Conversion error:", err);
      try {
        const fallbackCode = fallbackCurlToCode(req.body.curlCommand || "", target, req.body.options);
        return res.json({ success: true, code: fallbackCode, target });
      } catch (fallbackErr: any) {
        res.status(400).json({
          success: false,
          error: "cURL komutu ayrıştırılamadı. Lütfen komut biçimini kontrol edin."
        });
      }
    }
  });

  // Execute live API request preview
  app.post("/api/test-curl", async (req, res) => {
    try {
      const { url, method = "GET", headers = {}, data = null } = req.body;

      if (!url) {
        return res.status(400).json({ error: "Hedef URL bulunamadı." });
      }

      const startTime = Date.now();
      const reqHeaders: Record<string, string> = {};

      // Filter out problematic headers that interfere with Node fetch decompression or host routing
      for (const [k, v] of Object.entries(headers || {})) {
        const lowerKey = k.toLowerCase();
        if (["host", "content-length", "accept-encoding", "content-encoding", "connection"].includes(lowerKey)) {
          continue;
        }
        reqHeaders[k] = String(v);
      }

      if (!Object.keys(reqHeaders).some(k => k.toLowerCase() === "user-agent")) {
        reqHeaders["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36";
      }

      const options: RequestInit = {
        method,
        headers: reqHeaders,
      };

      if (data && ["POST", "PUT", "PATCH", "DELETE"].includes(method.toUpperCase())) {
        options.body = typeof data === "object" ? JSON.stringify(data) : String(data);
      }

      const response = await fetch(url, options);
      const endTime = Date.now();
      const durationMs = endTime - startTime;

      const responseHeaders: Record<string, string> = {};
      response.headers.forEach((val, key) => {
        responseHeaders[key] = val;
      });

      let bodyText = await response.text();
      let isJson = false;

      // Try parsing JSON regardless of exact Content-Type string
      try {
        const parsed = JSON.parse(bodyText);
        bodyText = JSON.stringify(parsed, null, 2);
        isJson = true;
      } catch {
        isJson = false;
      }

      // Detect Cloudflare or WAF Datacenter IP blocking
      const isWafBlock = response.status === 403 || response.status === 429 || response.status === 503 || bodyText.includes("Just a moment...") || bodyText.includes("Cloudflare") || bodyText.includes("Access Denied");

      res.json({
        success: true,
        status: response.status,
        statusText: response.statusText,
        durationMs,
        headers: responseHeaders,
        bodyText: bodyText.slice(0, 200000), // Cap at 200KB
        isJson,
        isWafBlock
      });
    } catch (err: any) {
      res.status(500).json({
        success: false,
        error: err.message || "İstek gönderilirken hata oluştu."
      });
    }
  });

  // Execute custom Python or JS code and return logs/response
  app.post("/api/run-code", async (req, res) => {
    try {
      const { code, target = "python-requests" } = req.body;

      if (!code || typeof code !== "string" || !code.trim()) {
        return res.status(400).json({ error: "Lütfen çalıştırılacak kod girin." });
      }

      const startTime = Date.now();
      const logs: string[] = [];

      // If JavaScript / Node code execution
      if (target.includes("javascript") || target.includes("nodejs") || code.includes("fetch(") || code.includes("axios")) {
        const sandboxConsole = {
          log: (...args: any[]) => logs.push(args.map(a => typeof a === 'object' ? JSON.stringify(a, null, 2) : String(a)).join(' ')),
          error: (...args: any[]) => logs.push("[HATA] " + args.map(a => typeof a === 'object' ? JSON.stringify(a, null, 2) : String(a)).join(' ')),
          warn: (...args: any[]) => logs.push("[UYARI] " + args.map(a => typeof a === 'object' ? JSON.stringify(a, null, 2) : String(a)).join(' ')),
        };

        const customFetch = async (...args: any[]) => {
          logs.push(`[İstek]: ${args[0]}`);
          const resp = await fetch(...(args as [any, any]));
          logs.push(`[Yanıt Statüsü]: ${resp.status} ${resp.statusText}`);
          return resp;
        };

        try {
          const fn = new Function(
            "fetch", "console", "JSON", "Math", "Date", "URLSearchParams",
            `return (async () => {\n${code}\n})();`
          );
          await fn(customFetch, sandboxConsole, JSON, Math, Date, URLSearchParams);
        } catch (jsErr: any) {
          logs.push(`[Kod Çalıştırma Hatası]: ${jsErr.message}`);
        }
      } else {
        // Python code simulation: Extract URL and parameters
        const urlMatch = code.match(/url\s*=\s*["']([^"']+)["']/i) || code.match(/(https?:\/\/[^\s"'`]+)/i);
        const url = urlMatch ? urlMatch[1] : null;

        if (!url) {
          return res.status(400).json({ error: "Kod içerisinde çalıştırılacak bir URL adresi bulunamadı." });
        }

        let method = "GET";
        if (/\.(post)\(/i.test(code) || /method\s*=\s*["']POST["']/i.test(code)) method = "POST";
        else if (/\.(put)\(/i.test(code) || /method\s*=\s*["']PUT["']/i.test(code)) method = "PUT";
        else if (/\.(delete)\(/i.test(code) || /method\s*=\s*["']DELETE["']/i.test(code)) method = "DELETE";
        else if (/\.(patch)\(/i.test(code) || /method\s*=\s*["']PATCH["']/i.test(code)) method = "PATCH";

        logs.push(`Python İcrası Simüle Ediliyor...`);
        logs.push(`[URL]: ${url}`);
        logs.push(`[Metod]: ${method}`);

        // Header parsing
        const headers: Record<string, string> = {};
        const headerMatches = code.matchAll(/["']([^"']+)["']\s*:\s*["']([^"']+)["']/g);
        for (const m of headerMatches) {
          const key = m[1];
          const val = m[2];
          const lowerKey = key.toLowerCase();
          if (!["url", "headers", "json_data", "data", "json", "params"].includes(lowerKey) &&
              !["host", "content-length", "accept-encoding", "content-encoding", "connection"].includes(lowerKey)) {
            headers[key] = val;
          }
        }

        if (!Object.keys(headers).some(k => k.toLowerCase() === "user-agent")) {
          headers["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36";
        }

        const options: RequestInit = { method, headers };

        // Payload extraction
        const jsonMatch = code.match(/json_data\s*=\s*(\{[\s\S]*?\n\})/);
        if (jsonMatch) {
          try {
            const bodyObj = JSON.parse(jsonMatch[1]);
            options.body = JSON.stringify(bodyObj);
            if (!Object.keys(headers).some(k => k.toLowerCase() === "content-type")) {
              headers["Content-Type"] = "application/json";
            }
          } catch {
            // ignore
          }
        }

        const response = await fetch(url, options);
        logs.push(`[Statü Kodu]: ${response.status} ${response.statusText}`);

        let responseBody = await response.text();
        try {
          const parsed = JSON.parse(responseBody);
          responseBody = JSON.stringify(parsed, null, 2);
        } catch {
          // Keep as text/html
        }

        const isWafBlock = response.status === 403 || response.status === 429 || response.status === 503 || responseBody.includes("Just a moment...") || responseBody.includes("Cloudflare") || responseBody.includes("Access Denied");

        if (isWafBlock) {
          logs.push(`\n[⚠️ WAF / BOT KORUMASI TESPİT EDİLDİ]`);
          logs.push(`Hedef API, Google Cloud bulut sunucu IP adresini engelledi (HTTP ${response.status}).`);
          logs.push(`ÖNEMLİ: Kodunuz tamamen doğrudur! Kodu indirip kendi bilgisayarınızda (Python ortamınızda) çalıştırdığınızda ev IP adresiniz ve yerel TLS katmanı sayesinde istediğiniz JSON yanıtı eksiksiz dönecektir.\n`);
        }

        logs.push(`=== KOD ÇIKTISI / YANIT BİLGİSİ ===\n${responseBody}`);
      }

      const endTime = Date.now();
      const durationMs = endTime - startTime;
      const outputText = logs.join("\n");

      res.json({
        success: true,
        durationMs,
        output: outputText,
        isJson: outputText.trim().startsWith("{") || outputText.trim().startsWith("[")
      });
    } catch (err: any) {
      res.status(500).json({
        success: false,
        error: err.message || "Kod çalıştırılırken sunucu hatası oluştu."
      });
    }
  });

  // Optional AI analysis / explanation / cURL fix
  app.post("/api/ai-analyze", async (req, res) => {
    try {
      const { curlCommand } = req.body;
      if (!curlCommand) {
        return res.status(400).json({ error: "cURL komutu gerekli." });
      }

      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        return res.json({
          success: false,
          error: "Gemini API anahtarı ayarlanmamış."
        });
      }

      const ai = new GoogleGenAI({ apiKey });
      const prompt = `Aşağıdaki cURL komutunu analiz et ve Türkçe olarak şunları sağla:
1. Bu istek tam olarak ne yapıyor? (Özet)
2. İstekte kullanılan HTTP Metodu, Endpoint, Başlıklar (Headers), Kimlik Doğrulama türü ve Veri (Payload) analizi.
3. Güvenlik İncelemesi (Açıkta duran API anahtarı, şifre, hassas token var mı?).
4. Python kodu kullanımında dikkat edilmesi gerekenler (Örn: Rate limit, Timeout, Exception Handling tavsiyeleri).

cURL Komutu:
\`\`\`bash
${curlCommand}
\`\`\`

Lütfen anlaşılır, Türkçe markdown formatında yanıt ver.`;

      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt
      });

      res.json({
        success: true,
        analysis: response.text
      });
    } catch (err: any) {
      res.status(500).json({
        success: false,
        error: err.message || "Yapay zeka analizi sırasında hata oluştu."
      });
    }
  });

  // Vite middleware setup
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

/**
 * Attempts conversion using curlconverter with smart validation,
 * guaranteeing data preservation via parseCurlAdvanced fallback if curlconverter drops data or fails.
 */
function convertCurlWithFallbacks(curlCommand: string, target: string, options: any): string {
  const info = parseCurlAdvanced(curlCommand);

  try {
    const code = invokeCurlConverter(curlCommand, target);

    // If cURL has data, verify that generated code actually includes data/payload
    if (info.hasBody && info.dataPayload) {
      const codeHasData =
        code.includes("data=") ||
        code.includes("json=") ||
        code.includes("content=") ||
        code.includes("json_data") ||
        code.includes("body:") ||
        code.includes("data:");

      if (!codeHasData) {
        // Fallback to advanced parser that guarantees payload inclusion
        return fallbackCurlToCode(curlCommand, target as any, options);
      }
    }

    return code;
  } catch {
    return fallbackCurlToCode(curlCommand, target as any, options);
  }
}

function invokeCurlConverter(curl: string, target: string): string {
  const conv = curlconverter as any;
  switch (target) {
    case "python-requests":
      return conv.toPython ? conv.toPython(curl) : fallbackCurlToCode(curl, target as any);
    case "python-httpx":
      return conv.toPythonHttp ? conv.toPythonHttp(curl) : fallbackCurlToCode(curl, target as any);
    case "python-httpx-async":
      if (conv.toPythonHttp) {
        let code = conv.toPythonHttp(curl);
        return convertToAsyncHttpx(code);
      }
      return fallbackCurlToCode(curl, target as any);
    case "javascript-fetch":
      return conv.toJavaScript ? conv.toJavaScript(curl) : fallbackCurlToCode(curl, target as any);
    case "nodejs-axios":
      return conv.toNode ? conv.toNode(curl) : fallbackCurlToCode(curl, target as any);
    default:
      return conv.toPython ? conv.toPython(curl) : fallbackCurlToCode(curl, target as any);
  }
}

function wrapTryExcept(code: string): string {
  const lines = code.split("\n");
  const imports: string[] = [];
  const body: string[] = [];

  for (const line of lines) {
    if (line.startsWith("import ") || line.startsWith("from ")) {
      imports.push(line);
    } else {
      body.push(line);
    }
  }

  const indentedBody = body.map((l) => (l ? "    " + l : "")).join("\n");

  return `${imports.join("\n")}\n\ntry:\n${indentedBody}\n    if 'response' in locals() and hasattr(response, 'raise_for_status'):\n        response.raise_for_status()\n        print("Başarılı! Statü Kodu:", getattr(response, 'status_code', 200))\nexcept Exception as e:\n    print("İstek hatası oluştu:", e)\n`;
}

function convertToAsyncHttpx(code: string): string {
  let asyncCode = code.replace(/import httpx/, "import httpx\nimport asyncio");
  asyncCode = asyncCode.replace(/response = httpx\.(get|post|put|delete|patch)\(/, "async with httpx.AsyncClient() as client:\n    response = await client.$1(");

  return `import asyncio\n${asyncCode}\n\n# Async çalıştırma örneği\n# asyncio.run(main())\n`;
}

startServer();
